package psych.server.data.dao.dto;

// Generated Sep 13, 2014 3:10:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GoalDTO generated by hbm2java
 */
public class GoalDTO implements java.io.Serializable {

	private String goalID;
	private String goalName;
	private String goalDescr;
	private String scoreType;
	private boolean archive;
	private Date addDt;
	private Date lastUpdateDt;

	public GoalDTO() {
	}

	public GoalDTO(String goalName, String scoreType) {
		this.goalName = goalName;
		this.scoreType = scoreType;
	}

	public GoalDTO(String goalName, String goalDescr, String scoreType,
			boolean archive, Date addDt, Date lastUpdateDt) {
		this.goalName = goalName;
		this.goalDescr = goalDescr;
		this.scoreType = scoreType;
		this.archive = archive;
		this.addDt = addDt;
		this.lastUpdateDt = lastUpdateDt;
	}

	public String getGoalID() {
		return this.goalID;
	}

	public void setGoalID(String goalID) {
		this.goalID = goalID;
	}

	public String getGoalName() {
		return this.goalName;
	}

	public void setGoalName(String goalName) {
		this.goalName = goalName;
	}

	public String getGoalDescr() {
		return this.goalDescr;
	}

	public void setGoalDescr(String goalDescr) {
		this.goalDescr = goalDescr;
	}

	public String getScoreType() {
		return this.scoreType;
	}

	public void setScoreType(String scoreType) {
		this.scoreType = scoreType;
	}

	public boolean isArchive() {
		return this.archive;
	}

	public void setArchive(boolean archive) {
		this.archive = archive;
	}

	public Date getAddDt() {
		return this.addDt;
	}

	public void setAddDt(Date addDt) {
		this.addDt = addDt;
	}

	public Date getLastUpdateDt() {
		return this.lastUpdateDt;
	}

	public void setLastUpdateDt(Date lastUpdateDt) {
		this.lastUpdateDt = lastUpdateDt;
	}

}
