package psych.server.data.dao.dto;

// Generated Sep 13, 2014 3:10:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * PropertyPK generated by hbm2java
 */
public class PropertyPK implements java.io.Serializable {

	private String propertyId;
	private PropertyCategoryDTO catInfo;

	public PropertyPK() {
	}

	public PropertyPK(String propertyId, PropertyCategoryDTO catInfo) {
		this.propertyId = propertyId;
		this.catInfo = catInfo;
	}

	public String getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(String propertyId) {
		this.propertyId = propertyId;
	}

	public PropertyCategoryDTO getCatInfo() {
		return this.catInfo;
	}

	public void setCatInfo(PropertyCategoryDTO catInfo) {
		this.catInfo = catInfo;
	}

}
