package psych.server.data.dao.dto;

// Generated Sep 13, 2014 3:10:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PropertyCategoryDTO generated by hbm2java
 */
public class PropertyCategoryDTO implements java.io.Serializable {

	private String catId;
	private String catName;
	private String catDescr;
	private Set<PropertyDTO> properties = new HashSet<PropertyDTO>(0);

	public PropertyCategoryDTO() {
	}

	public PropertyCategoryDTO(String catId, String catName, String catDescr) {
		this.catId = catId;
		this.catName = catName;
		this.catDescr = catDescr;
	}

	public PropertyCategoryDTO(String catId, String catName, String catDescr,
			Set<PropertyDTO> properties) {
		this.catId = catId;
		this.catName = catName;
		this.catDescr = catDescr;
		this.properties = properties;
	}

	public String getCatId() {
		return this.catId;
	}

	public void setCatId(String catId) {
		this.catId = catId;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getCatDescr() {
		return this.catDescr;
	}

	public void setCatDescr(String catDescr) {
		this.catDescr = catDescr;
	}

	public Set<PropertyDTO> getProperties() {
		return this.properties;
	}

	public void setProperties(Set<PropertyDTO> properties) {
		this.properties = properties;
	}

}
