package psych.server.data.dao.dto;

// Generated Sep 13, 2014 3:10:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ScoreDTO generated by hbm2java
 */
public class ScoreDTO implements java.io.Serializable {

	private String scoreID;
	private String scoreStatus;
	private Integer scoreCnt;
	private String scoreNote;
	private Date addDt;
	private Date lastUpdateDt;
	private GoalDTO goalDTO;

	public ScoreDTO() {
	}

	public ScoreDTO(GoalDTO goalDTO) {
		this.goalDTO = goalDTO;
	}

	public ScoreDTO(String scoreStatus, Integer scoreCnt, String scoreNote,
			Date addDt, Date lastUpdateDt, GoalDTO goalDTO) {
		this.scoreStatus = scoreStatus;
		this.scoreCnt = scoreCnt;
		this.scoreNote = scoreNote;
		this.addDt = addDt;
		this.lastUpdateDt = lastUpdateDt;
		this.goalDTO = goalDTO;
	}

	public String getScoreID() {
		return this.scoreID;
	}

	public void setScoreID(String scoreID) {
		this.scoreID = scoreID;
	}

	public String getScoreStatus() {
		return this.scoreStatus;
	}

	public void setScoreStatus(String scoreStatus) {
		this.scoreStatus = scoreStatus;
	}

	public Integer getScoreCnt() {
		return this.scoreCnt;
	}

	public void setScoreCnt(Integer scoreCnt) {
		this.scoreCnt = scoreCnt;
	}

	public String getScoreNote() {
		return this.scoreNote;
	}

	public void setScoreNote(String scoreNote) {
		this.scoreNote = scoreNote;
	}

	public Date getAddDt() {
		return this.addDt;
	}

	public void setAddDt(Date addDt) {
		this.addDt = addDt;
	}

	public Date getLastUpdateDt() {
		return this.lastUpdateDt;
	}

	public void setLastUpdateDt(Date lastUpdateDt) {
		this.lastUpdateDt = lastUpdateDt;
	}

	public GoalDTO getGoalDTO() {
		return this.goalDTO;
	}

	public void setGoalDTO(GoalDTO goalDTO) {
		this.goalDTO = goalDTO;
	}

}
