package psych.server.data.dao.dto;

// Generated Sep 13, 2014 3:10:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * SystemProfileDTO generated by hbm2java
 */
public class SystemProfileDTO implements java.io.Serializable {

	private String systemProfileID;
	private String profileName;
	private String profileDescr;

	public SystemProfileDTO() {
	}

	public SystemProfileDTO(String systemProfileID, String profileName) {
		this.systemProfileID = systemProfileID;
		this.profileName = profileName;
	}

	public SystemProfileDTO(String systemProfileID, String profileName,
			String profileDescr) {
		this.systemProfileID = systemProfileID;
		this.profileName = profileName;
		this.profileDescr = profileDescr;
	}

	public String getSystemProfileID() {
		return this.systemProfileID;
	}

	public void setSystemProfileID(String systemProfileID) {
		this.systemProfileID = systemProfileID;
	}

	public String getProfileName() {
		return this.profileName;
	}

	public void setProfileName(String profileName) {
		this.profileName = profileName;
	}

	public String getProfileDescr() {
		return this.profileDescr;
	}

	public void setProfileDescr(String profileDescr) {
		this.profileDescr = profileDescr;
	}

}
