package psych.server.data.dao.dto;

// Generated Sep 13, 2014 3:10:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * SystemRoleDTO generated by hbm2java
 */
public class SystemRoleDTO implements java.io.Serializable {

	private String systemRoleID;
	private String systemRoleName;
	private String descr;

	public SystemRoleDTO() {
	}

	public SystemRoleDTO(String systemRoleID, String systemRoleName,
			String descr) {
		this.systemRoleID = systemRoleID;
		this.systemRoleName = systemRoleName;
		this.descr = descr;
	}

	public String getSystemRoleID() {
		return this.systemRoleID;
	}

	public void setSystemRoleID(String systemRoleID) {
		this.systemRoleID = systemRoleID;
	}

	public String getSystemRoleName() {
		return this.systemRoleName;
	}

	public void setSystemRoleName(String systemRoleName) {
		this.systemRoleName = systemRoleName;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

}
